name: slconnect
version: 1.0.0+1
publish_to: none
description: A new Flutter project.
environment: 
  sdk: '>=2.19.6 <3.0.0'

dependencies: 
  cupertino_icons: ^1.0.2
  get: 4.6.5
  lottie: ^2.3.2
  firebase_core: ^2.10.0
  firebase_auth: ^4.4.2
  pinput: 2.2.31
  cloud_firestore: 4.7.0
  flutter: 
    sdk: flutter
  shared_preferences: ^2.1.1

dev_dependencies: 
  flutter_lints: 2.0.1
  flutter_test: 
    sdk: flutter

flutter: 
  assets: 
    - assets/images/
    - assets/lottie/
  uses-material-design: true

