name: slconnect
version: 1.0.0+1
publish_to: none
description: A new Flutter project.
environment: 
  sdk: '>=2.19.6 <3.0.0'

dependencies: 
  cupertino_icons: ^1.0.2
  get: 4.6.5
  lottie: ^2.3.2
  firebase_core: ^2.10.0
  firebase_auth: ^4.4.2
  pinput: 2.2.31
  cloud_firestore: 4.7.0
  flutter: 
    sdk: flutter
  shared_preferences: ^2.1.1
  google_fonts: ^4.0.4
  iconify_flutter: ^0.0.5
  firebase_messaging: ^14.6.1
  overlay_support: ^2.1.0
  onesignal_flutter: ^3.5.1
  flutter_native_splash: ^2.3.1
  autocomplete_textfield: ^2.0.1
  table_calendar: ^3.0.9
flutter_native_splash:
  android: true
  ios: false
  web: false
  color: "#FFFFFF"
  image: "assets/images/splash_screen.png"
dev_dependencies: 
  flutter_lints: 2.0.1
  flutter_test: 
    sdk: flutter
  flutter_launcher_icons:
flutter_launcher_icons:
  android: "launcher_icon"
  ios: false
  image_path: "assets/images/splash_screen.png"
flutter: 
  assets: 
    - assets/images/
    - assets/lottie/
  uses-material-design: true

